void#processExceptions#(#)#{#taskException#=#testException#;##//look for an application fault##if#(#applicationException#!=#null#)#{##if#(#taskException#==#null#||#taskException#instanceof#BuildTimeoutException#)#{#taskException#=#applicationException#;#}#else#{#ignoringThrowable#(#APPLICATION_EXCEPTION#,#applicationException#)#;#}#}##//now look for teardown faults, which may be ignored##if#(#teardownException#!=#null#)#{##if#(#taskException#==#null#&&#failOnTeardownErrors#)#{#taskException#=#teardownException#;#}#else#{##//don't let the cleanup exception get in the way of any other failure#ignoringThrowable#(#TEARDOWN_EXCEPTION#,#teardownException#)#;#}#}##//now, analyse the tests##if#(#failureProperty#!=#null#&&#getProject#(#)#.#getProperty#(#failureProperty#)#!=#null#)#{##//we've failed#log#(#failureMessage#)#;##if#(#taskException#==#null#)#{#taskException#=#new#BuildException#(#failureMessage#)#;#}#}##//at this point taskException is null or not.##//if not, throw the exception##if#(#taskException#!=#null#)#{#throw#taskException#;#}#}