void#testNoSuite#(#)#{#TestRunner#runner#=#createRunner#(#NoSuiteTestCase#.#class#)#;#runner#.#run#(#)#;#assertEquals#(#runner#.#getFormatter#(#)#.#getError#(#)#,#JUnitTestRunner#.#SUCCESS#,#runner#.#getRetCode#(#)#)#;#}##void#testSuite#(#)#{#TestRunner#runner#=#createRunner#(#SuiteTestCase#.#class#)#;#runner#.#run#(#)#;#assertEquals#(#runner#.#getFormatter#(#)#.#getError#(#)#,#JUnitTestRunner#.#SUCCESS#,#runner#.#getRetCode#(#)#)#;#}##void#testInvalidSuite#(#)#{#TestRunner#runner#=#createRunner#(#InvalidSuiteTestCase#.#class#)#;#runner#.#run#(#)#;#String#error#=#runner#.#getFormatter#(#)#.#getError#(#)#;#assertEquals#(#error#,#JUnitTestRunner#.#ERRORS#,#runner#.#getRetCode#(#)#)#;#assertTrue#(#error#,#error#.#indexOf#(#"thrown on purpose"#)#!=#-#1#)#;#}##void#testNoTestCase#(#)#{#TestRunner#runner#=#createRunner#(#NoTestCase#.#class#)#;#runner#.#run#(#)#;#// On junit3 this is a FAILURE, on junit4 this is an ERROR#int#ret#=#runner#.#getRetCode#(#)#;#if#(#ret#!=#JUnitTestRunner#.#FAILURES#&&#ret#!=#JUnitTestRunner#.#ERRORS#)#{#fail#(#"Unexpected result "#+#ret#+#" from junit runner"#)#;#}#// JUnit3 test#//assertEquals(runner.getFormatter().getError(), JUnitTestRunner.FAILURES, runner.getRetCode());#}##void#testInvalidTestCase#(#)#{#TestRunner#runner#=#createRunner#(#InvalidTestCase#.#class#)#;#runner#.#run#(#)#;#// On junit3 this is a FAILURE, on junit4 this is an ERROR#int#ret#=#runner#.#getRetCode#(#)#;#if#(#ret#!=#JUnitTestRunner#.#FAILURES#&&#ret#!=#JUnitTestRunner#.#ERRORS#)#{#fail#(#"Unexpected result "#+#ret#+#" from junit runner"#)#;#}#// JUNIT3 test#//assertEquals(error, JUnitTestRunner.FAILURES, runner.getRetCode());#//@fixme as of now does not report the original stacktrace.#//assertTrue(error, error.indexOf("thrown on purpose") != -1);#}##TestRunner#createRunner#(#Class#clazz#)#{#return#new#TestRunner#(#new#JUnitTest#(#clazz#.#getName#(#)#)#,#true#,#true#,#true#)#;#}##ResultFormatter#getFormatter#(#)#{#return#formatter#;#}##void#setSystemOutput#(#String#output#)#{#}##void#setSystemError#(#String#output#)#{#}##void#startTestSuite#(#JUnitTest#suite#)#throws#BuildException#{#}##void#endTestSuite#(#JUnitTest#suite#)#throws#BuildException#{#}##void#setOutput#(#java#.#io#.#OutputStream#out#)#{#}##void#startTest#(#Test#t#)#{#}##void#endTest#(#Test#test#)#{#}##void#addFailure#(#Test#test#,#Throwable#t#)#{#}##void#addFailure#(#Test#test#,#AssertionFailedError#t#)#{#}##void#addError#(#Test#test#,#Throwable#t#)#{#error#=#t#;#}##String#getError#(#)#{#if#(#error#==#null#)#{#return#""#;#}#StringWriter#sw#=#new#StringWriter#(#)#;#error#.#printStackTrace#(#new#PrintWriter#(#sw#)#)#;#return#sw#.#toString#(#)#;#}##void#testA#(#)#{#}##Test#suite#(#)#{#return#new#TestSuite#(#SuiteTestCase#.#class#)#;#}##Test#suite#(#)#{#throw#new#NullPointerException#(#"thrown on purpose"#)#;#}##void#main#(#String#[#]#args#)#{#junit#.#textui#.#TestRunner#.#run#(#JUnitTestRunnerTest#.#class#)#;#}##